# Generated by Django 4.1 on 2022-08-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='active_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', models.CharField(max_length=255, verbose_name='Дело')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
        ),
    ]
