# Generated by Django 4.1 on 2022-08-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='active_list',
            new_name='ActiveList',
        ),
    ]
