# Generated by Django 4.1 on 2022-08-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_rename_active_list_activelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelist',
            name='done_date',
            field=models.DateTimeField(null=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='activelist',
            name='deal',
            field=models.CharField(max_length=58, verbose_name='Дело'),
        ),
    ]
