# Generated by Django 4.1 on 2022-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_activelist_done_date_alter_activelist_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelist',
            name='days',
            field=models.IntegerField(null=True, verbose_name='Дней выполнения'),
        ),
        migrations.AddField(
            model_name='activelist',
            name='hours',
            field=models.IntegerField(null=True, verbose_name='Часов выполнения'),
        ),
        migrations.AddField(
            model_name='activelist',
            name='minutes',
            field=models.IntegerField(null=True, verbose_name='Минут выполнения'),
        ),
        migrations.AddField(
            model_name='activelist',
            name='seconds',
            field=models.IntegerField(null=True, verbose_name='Секунд выполнения'),
        ),
    ]
